---

development: &default

test:
  <<: *default

staging:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

production:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

